config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users
  resources :articles do
    resources :comments
  end
  get "/topics", to: "topics#index"
  get "/topics/:id", to: "topics#new"
  root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :body
  has_one_attached :thumbnail, dependent: :destroy
  has_many :topics
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, :body, :thumbnail, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :body, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :username, :description, :avatar, :password, :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password, :password_confirmation, :description, :avatar])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :search_article

  def index

  end

  def new
    @article = Article.new
    render layout: "new_article"
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      flash.notice = "Article saved successfully"
      redirect_to articles_path
    else
      if @article.title == "" or @article.body == ""
        flash.alert = "There must be some text in (Title and Body) and Thumbnail must be present"
      end
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
    render layout: "new_article"
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @article = current_user.articles.find (params[:id])
    @article.destroy
    redirect_to user_path(current_user)
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :thumbnail)
  end

  def search_article
    @q = Article.ransack(params[:q])
    @pagy, @articles = pagy(@q.result, items: 4)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_article

  def index
    @comments = Comment.all
  end

  def create
    @comment = @article.comments.new(comment_params.merge(user_id: current_user.id))
    if @comment.save
      redirect_to article_path(@article)
    end
  end

  def edit
    @comment = @article.comments.find(params[:id])
    render layout: "new_article"
  end

  def update
    @comment = @article.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to article_path(@article)
    end
  end

  def destroy
    @comment = @article.comments.find(params[:comment_id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article
    @article = Article.find params[:article_id]
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  layout 'new_article'
  def index
    @topics = Topic.all
    @pagy, @articles = pagy(@topics, items: 4)
  end
  def new
    @topic = Topic.find(params[:id])
    @article = Article.new(title: @topic.title, body: @topic.description )
  end
  def create

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @q = User.find(params[:id]).articles.ransack(params[:q])
    @pagy, @userArticles = pagy(@q.result, items: 4)
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [800, 600] : [1024, 768]) %>
  <% end %>
</figure>

app/views/articles/_new_article_form.html.erb
<%= form_with model: @article do |form| %>
  <div class="field margin-lrtb">
    <%= form.text_field :title, placeholder: " Title", class: "new-article-form-title w-100" %>
  </div>
  <div class="field margin-lrtb">
    <%= form.label :"Thumbnail: ", class: "fw-bold" %>
    <%= form.file_field :thumbnail %>
  </div>
  <div>
    <div class="field margin-lrtb">
      <%= form.rich_text_area :body, placeholder: "Body" %>
    </div>
  </div>
  <div class="actions margin-lrtb">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render "new_article_form" %>

app/views/articles/index.html.erb
<%= render "layouts/index_article_div" %>

app/views/articles/new.html.erb
<%= render "new_article_form" %>

app/views/articles/show.html.erb
<div class="margin-lrtb">
  <h3 class="index-article-title"><%= @article.title %></h3>
  <%= @article.body %>
  <%= render "comments/article_comments" %>
  <%= render "comments/form", comment: @article.comments.build %>
</div>

app/views/comments/_article_comments.html.erb
<div class="mt-5">
  <h3 class="comments">comments:</h3>
  <% @article.comments.each do |comment| %>
    <ul class="comments">
      <li class="login-user-image">
        <div>
          <%= image_tag comment.user.avatar %>
          <span class="header-user-name">
          <%= comment.user.username %>
        </span>
        </div>
        <div class="mt-2">
          <%= comment.body %>
          <div class="mt-2">
            <% if comment.user.id == current_user.id %>
              <%= link_to "Edit", edit_article_comment_path(article_id: @article, id: comment.id) %>
              <%= link_to "Delete", article_comment_path(article_id: @article, comment_id: comment.id), data: { turbo_method: :delete } %>
            <% end %>
          </div>
        </div>
      </li>
    </ul>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@article, comment] do |form| %>
  <div class="field margin-lrtb">
    <%= form.text_field :body, placeholder: " Place a comment", class: "new-article-form-title w-100" %>
  </div>
  <div class="actions margin-lrtb">
    <% form.submit %>
  </div>
<% end %>

app/views/comments/_new_comment.html.erb
<!--<h3 class="comments">comments:</h3>-->
<%# @article.comments.each do |comment| %>
<!--  <ul class="comments">-->
<!--    <li class="login-user-image">-->
<!--      <div>-->
        <%#= image_tag comment.user.avatar %>
<!--        <span class="header-user-name">-->
          <%#= comment.user.username %>
<!--        </span>-->
<!--      </div>-->
<!--      <div class="mt-2">-->
        <%#= comment.body %>
<!--      </div>-->
<!--    </li>-->
<!--  </ul>-->
<%# end %>
<%#= form_with model: [@article, @article.comments.build] do |form| %>
<!--  <div class="field margin-lrtb">-->
    <%#= form.text_field :body, placeholder: " comment", class: "new-article-form-title w-100" %>
<!--  </div>-->
<!--  <div class="actions margin-lrtb">-->
    <%# form.submit %>
<!--  </div>-->
<%# end %>

app/views/comments/edit.html.erb
<%= render "comments/form",comment: @comment %>

app/views/comments/new.html.erb
<%= render "new_comment" %>

app/views/layouts/_article_search.html.erb
<%= search_form_for @q do |f| %>
  <%= f.search_field :title_cont, class: "form-control index-search-bar mt-5", placeholder: "Search" %>
  <% f.submit %>
<% end %>

app/views/layouts/_flash_message.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_full_screen_navagation_bar.html.erb
<div class="index-nevegation-bar">
  <%= link_to root_path do %>
    <% image_tag("medium_icon.png") %>
  <% end %>
  <div class="links justify-content-around">
    <%= link_to root_path do %>
      <span class="w3-xlarge fa fa-home "></span>
    <% end %>
    <%= link_to user_path(current_user) do %>
      <span class="w3-xlarge fas fa-folder-open"></span>
    <% end %>
    <%= link_to topics_path do %>
      <span class="w3-xlarge fa fa-user"></span>
    <% end %>
    <hr>
    <%= link_to new_article_path do %>
      <span class="w3-xlarge far fa-edit"></span>
    <% end %>
  </div>
  <%= link_to root_path, class: "login-user-image" do %>
    <% if current_user.avatar.attached? %>
      <%= image_tag current_user.avatar %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_index_article_div.html.erb
<% @articles.each do |article| %>
  <div class="homepage-article-raper">
    <hr>
    <div class="d-flex">
      <% if article.user.avatar.attached? %>
        <%= image_tag article.user.avatar.representation(resize_to_limit: [20, 20]), class: "b-radius-50", width: 22 %>
      <% end %>
      <span class="header-user-name">
        <%= article.user.username %>
      </span>
      . <%= article.created_at.strftime("%b %d,%Y") %>
    </div>
    <div class="article-image-reper mt-2 d-none d-md-flex">
      <a class="index-article" target="_blank" href="<%= article_path(article) %>">
        <h2 class="index-article-title index-article-title-raper"><%= article.title %></h2>
        <div class="index-article-body-raper d-none d-md-block">
          <p class="index-article-body"><%= article.body %></p>
        </div>
      </a>
      <div class="index-article-image d-none d-md-block">
        <% if article.thumbnail.representable? %>
          <%= image_tag article.thumbnail.representation(resize_to_limit: [200, 100]) %>
        <% end %>
      </div>
    </div>
    <div class="small-screen-article-and-image-reper mt-2 d-md-none">
      <div class="index-article">
        <a class="index-article" target="_blank" href="<%= article_path(article) %>">
          <div class="small-screen-index-article-title">
            <h2 class="small-screen-index-article-title"><%= article.title %></h2>
          </div>
          <div class="index-article-body-raper d-none ">
            <p class="index-article-body"><%= article.body %></p>
          </div>
        </a>
      </div>
      <div class="index-small-screen-article-image">
        <% if article.thumbnail.representable? %>
          <%= image_tag article.thumbnail.representation(resize_to_limit: [200, 100]) %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="index-pagy-nave ">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/layouts/_small_screen_nevagation_bar.html.erb
<div class="d-xl-none bg-white d-flex justify-content-center small-screen-nevegation-bar">
  <div class="col-2">
    <%= link_to root_path do %>
      <span class="w3-xlarge fa fa-home td-non"></span>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to user_path(current_user.id) do %>
      <span class="w3-xlarge fas fa-folder-open td-non"></span>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to root_path do %>
      <span class="w3-xlarge fa fa-user td-non"></span>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to root_path do %>
      <span class="w3-xlarge fa fa-search td-non"></span>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to new_article_path do %>
      <span class="w3-xlarge far fa-edit td-non"></span>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to root_path, class: "login-user-image" do %>
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_user_session_status.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>MediumDemoProject</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<%= render "layouts/flash_message" %>
<% if user_signed_in? %>
  <div class="index-main-div">
    <div class="row">
      <div class="d-none d-xl-block col-xl-1 col-xxl-2   ">
        <%= render "layouts/full_screen_navagation_bar" %>
      </div>
      <div class="d-sm-block d-sm-11 col-xl-8 col-xxl-7 border-start border-end justify-content-center new-article-action-text ">
        <%= yield %>
      </div>
      <div class="d-none d-xl-block col-xl-3 ">
        <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "mt-5" %>
        <%= render "layouts/article_search" %>
      </div>
    </div>
    <%= render "layouts/small_screen_nevagation_bar" %>
  </div>
<% else %>
  <%= yield %>
<% end %>
</body>
</html>

app/views/layouts/new_article.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>MediumDemoProject</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<%= render "layouts/flash_message" %>
<% if user_signed_in? %>
  <div class="index-main-div">
    <div class="row">
      <div class="d-none d-xl-block col-xl-1 col-xxl-2   ">
        <%= render "layouts/full_screen_navagation_bar" %>
      </div>
      <div class="d-sm-block d-sm-11 col-xl-8 col-xxl-7 border-start border-end justify-content-center new-article-action-text ">
        <div class="mt-5">
          <%= yield %>
        </div>
      </div>
      <div class="d-none d-xl-block col-xl-3 ">
      </div>
    </div>
    <%= render "layouts/small_screen_nevagation_bar" %>
  </div>
<% else %>
  <%= yield %>
<% end %>
</body>
</html>

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
  <div class="homepage-article-raper">
    <hr>
    <div class="article-image-reper mt-2 d-none d-md-flex">
      <div class="index-article">
        <a class="t-decoration" target="_blank" href="/topics/<%=topic.id%>">
          <h2 class="index-article-title index-article-title-raper"><%= topic.title %></h2>
          <div class="index-article-body-raper d-none d-md-block">
            <p class="index-article-body"><%= topic.description %></p>
          </div>
        </a>
      </div>
    </div>
    <div class="small-screen-article-and-image-reper mt-2 d-md-none">
      <div class="index-article">
        <a class="t-decoration" target="_blank" href="<%= topics_path(topic.id) %>">
          <div class="small-screen-index-article-title">
            <h2 class="small-screen-index-article-title"><%= topic.title %></h2>
          </div>
          <div class="index-article-body-raper d-none ">
            <p class="index-article-body"><%= topic.description %></p>
          </div>
        </a>
      </div>
    </div>
  </div>
<% end %>
<div class="index-pagy-nave ">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/topics/new.html.erb
<%= render "articles/new_article_form" %>

app/views/users/_users_article.html.erb
<% @userArticles.each do |article| %>
  <div class="homepage-article-raper">
    <hr>
    <div class="article-image-reper mt-2 d-none d-md-flex">
      <div class="index-article">
        <a class="t-decoration" target="_blank" href="<%= article_path(article) %>">
          <h2 class="index-article-title index-article-title-raper"><%= article.title %></h2>
          <div class="index-article-body-raper d-none d-md-block">
            <p class="index-article-body"><%= article.body %></p>
          </div>
        </a>
        <%= link_to "Edit", edit_article_path(article) %>
        <%= link_to "Delete", article_path(article), data: { turbo_method: :delete } %>
      </div>
      <div class="index-article-image d-none d-md-block">
        <% if article.thumbnail.attached? %>
          <%= image_tag article.thumbnail.representation(resize_to_limit: [200, 100]) %>
        <% end %>
      </div>
    </div>
    <div class="small-screen-article-and-image-reper mt-2 d-md-none">
      <div class="index-article">
        <a class="t-decoration" target="_blank" href="<%= article_path(article) %>">
        <div class="small-screen-index-article-title">
            <h2 class="small-screen-index-article-title"><%= article.title %></h2>
        </div>
        <div class="index-article-body-raper d-none ">
          <p class="index-article-body"><%= article.body %></p>
        </div>
        </a>
        <%= link_to "Edit", edit_article_path(article) %>
        <%= link_to "Delete", article_path(article), data: { turbo_method: :delete } %>
      </div>
      <div class="index-small-screen-article-image">
        <% if article.thumbnail.attached? %>
          <%= image_tag article.thumbnail.representation(resize_to_limit: [200, 100]) %>
        <% end %>
      </div>
      <div class="index-small-screen-article-image">
        <% if article.thumbnail.attached? %>
          <%= image_tag article.thumbnail.representation(resize_to_limit: [200, 100]) %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="index-pagy-nave ">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/users/show.html.erb
<%= render "users/users_article" %>